server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: syncstream-backend
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/syncstream}
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}

app:
  jwt:
    secret: ${JWT_SECRET:5573796e6353747265616d53757065725365637265744b65793230323623}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours in ms
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost:5173}
